version: '3'
services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      PYTHONUNBUFFERED: 1
  frontend:
    build: ./frontend
    command: serve -s build -p 3000
    ports:
      - "3000:3000"
