# Generated by Django 3.0.5 on 2020-04-04 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_day', models.DateField()),
                ('sku', models.TextField()),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=16)),
                ('revenue', models.DecimalField(decimal_places=4, max_digits=16)),
                ('earnings', models.DecimalField(decimal_places=4, max_digits=16)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_user', to=settings.AUTH_USER_MODEL)),
                ('reporting_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
